[package]
name = "propagon"
version = "0.1.7"
authors = ["Andrew Stanton <refefer@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.26.0"
random = "0.12.2"
rand = "0.7.2"
rand_xorshift = "0.2.0"
rand_distr = "0.2.0"
rayon = "1.0.3"
heap = "0.1.0"
thread_local = "1.0.0"
indicatif = "0.13.0"
float-ord = "0.2.0"
ahash = "0.6.1"
statrs = " 0.15.0"

[dependencies.hashbrown]
version = "0.9.1"
features = ["rayon"]
