# Type stubs for the compiled propagon._propagon extension.
#
# Unit-valued enum parameters are passed as strings (serde kebab-case); the
# accepted literals are noted in each constructor's docstring in the Rust source.
from typing import Optional

__version__: str
__all__: list[str]

# --------------------------------------------------------------------------- #
# Exceptions
# --------------------------------------------------------------------------- #
class PropagonError(Exception): ...
class InvalidInputError(PropagonError): ...
class EmptyDatasetError(PropagonError): ...
class NumericError(PropagonError): ...
class StateError(PropagonError): ...
class AlgorithmMismatchError(StateError): ...
class ParamMismatchError(PropagonError): ...
class IoError(PropagonError): ...

# --------------------------------------------------------------------------- #
# Value types
# --------------------------------------------------------------------------- #
class PlayerState:
    @property
    def r(self) -> float: ...
    @property
    def rd(self) -> float: ...
    @property
    def sigma(self) -> float: ...
    def bounds(self) -> tuple[float, float]: ...

class Rating:
    @property
    def mu(self) -> float: ...
    @property
    def sigma(self) -> float: ...

# --------------------------------------------------------------------------- #
# Parameter enums (data-carrying; unit enums are plain strings)
# --------------------------------------------------------------------------- #
class GameOutcome:
    @classmethod
    def side1_win(cls, margin: float = 1.0) -> GameOutcome: ...
    @classmethod
    def side2_win(cls, margin: float = 1.0) -> GameOutcome: ...
    @classmethod
    def tie(cls) -> GameOutcome: ...

class BanditPolicy:
    @classmethod
    def greedy(cls) -> BanditPolicy: ...
    @classmethod
    def epsilon_greedy(cls, epsilon: float) -> BanditPolicy: ...
    @classmethod
    def ucb1(cls, exploration: float) -> BanditPolicy: ...
    @classmethod
    def thompson_beta(cls, prior_alpha: float, prior_beta: float) -> BanditPolicy: ...
    @classmethod
    def thompson_gaussian(cls, prior_mean: float, prior_weight: float) -> BanditPolicy: ...
    @classmethod
    def kl_ucb(cls, c: float) -> BanditPolicy: ...
    @classmethod
    def exp3(cls, gamma: float) -> BanditPolicy: ...

class DuelingPolicy:
    @classmethod
    def rucb(cls, alpha: float) -> DuelingPolicy: ...
    @classmethod
    def double_thompson(cls, alpha: float) -> DuelingPolicy: ...

class Granularity:
    @classmethod
    def global_(cls) -> Granularity: ...
    @classmethod
    def per_state(cls, separator: str) -> Granularity: ...

class SourceBudget:
    @classmethod
    def all(cls) -> SourceBudget: ...
    @classmethod
    def sample(cls, count: int, seed: int) -> SourceBudget: ...

class KemenyPasses:
    @classmethod
    def auto(cls) -> KemenyPasses: ...
    @classmethod
    def fixed(cls, n: int) -> KemenyPasses: ...

class Winsorize:
    @classmethod
    def off(cls) -> Winsorize: ...
    @classmethod
    def percentile(cls, percentile: float) -> Winsorize: ...

class Teleport:
    @classmethod
    def uniform(cls) -> Teleport: ...
    @classmethod
    def seeds(cls, seeds: list[tuple[str, float]]) -> Teleport: ...

class PairwiseTests:
    @classmethod
    def off(cls) -> PairwiseTests: ...
    @classmethod
    def on(cls, permutations: int) -> PairwiseTests: ...

# --------------------------------------------------------------------------- #
# Datasets
# --------------------------------------------------------------------------- #
class PairwiseDataset:
    def __init__(self) -> None: ...
    def push(self, winner: str, loser: str, weight: float = 1.0) -> None: ...
    def new_period(self) -> None: ...
    def n_entities(self) -> int: ...
    def n_periods(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...

class GamesDataset:
    def __init__(self) -> None: ...
    def push_pair(self, winner: str, loser: str, weight: float = 1.0) -> None: ...
    def push_game(
        self, side1: list[str], side2: list[str], outcome: GameOutcome, weight: float = 1.0
    ) -> None: ...
    def new_period(self) -> None: ...
    def n_entities(self) -> int: ...
    def n_periods(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...

class GraphDataset:
    def __init__(self) -> None: ...
    def push(self, src: str, dst: str, weight: float = 1.0) -> None: ...
    def n_nodes(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...

class RewardsDataset:
    def __init__(self) -> None: ...
    def push(self, arm: str, reward: float) -> None: ...
    def n_arms(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...

class ContextualRewardsDataset:
    def __init__(self) -> None: ...
    def push(self, arm: str, reward: float, x: list[float]) -> None: ...
    def n_arms(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...

class MatchupsDataset:
    def __init__(self) -> None: ...
    def push_match(self, teams: list[list[str]], ranks: list[int]) -> None: ...
    def n_entities(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...

class AnnotatedPairsDataset:
    def __init__(self) -> None: ...
    def push(self, annotator: str, winner: str, loser: str, weight: float = 1.0) -> None: ...
    def n_entities(self) -> int: ...
    def n_annotators(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...

class RankingsDataset:
    def __init__(self) -> None: ...
    def push_ranking(self, ranking: list[str]) -> None: ...
    def n_entities(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...

class TrajectoriesDataset:
    def __init__(self) -> None: ...
    def push_step(self, state: str, reward: float) -> None: ...
    def end_episode(self) -> None: ...
    def n_entities(self) -> int: ...
    def n_episodes(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...

# --------------------------------------------------------------------------- #
# Models: common surface (every model class supports these)
# --------------------------------------------------------------------------- #
class _Model:
    @property
    def algorithm(self) -> str: ...
    def scores(self) -> dict[str, float]: ...
    def sorted_scores(self) -> list[tuple[str, float]]: ...
    def score(self, name: str) -> Optional[float]: ...
    def top(self, k: int) -> list[tuple[str, float]]: ...
    def save_state(self) -> str: ...
    def save_state_bytes(self) -> bytes: ...
    @classmethod
    def load(cls, text: str) -> _Model: ...

class EloModel(_Model): ...
class Glicko2Model(_Model):
    def players(self) -> list[tuple[str, PlayerState]]: ...
class MovEloModel(_Model): ...
class MEloModel(_Model): ...
class GeneralizedBtModel(_Model): ...
class TeamBradleyTerryModel(_Model): ...
class PageRankModel(_Model): ...
class HitsModel(_Model): ...
class BiRankModel(_Model): ...
class DegreeModel(_Model): ...
class HarmonicModel(_Model): ...
class KatzModel(_Model): ...
class KCoreModel(_Model): ...
class LeaderRankModel(_Model): ...
class BanditModel(_Model): ...
class SlidingWindowUcbModel(_Model): ...
class LinUcbModel(_Model): ...
class CrowdBtModel(_Model): ...
class WengLinModel(_Model):
    def ratings(self) -> list[tuple[str, Rating]]: ...
class PlackettLuceModel(_Model): ...
class FootruleModel(_Model): ...
class MallowsModel(_Model): ...
class Mc4Model(_Model): ...
class McValueModel(_Model): ...
class BehaviorCloningModel(_Model): ...
class ValueCompareModel(_Model): ...
class TdValueModel(_Model): ...
class BradleyTerryMMModel(_Model): ...
class BradleyTerryLRModel(_Model): ...
class BayesianBradleyTerryModel(_Model): ...
class ColleyModel(_Model): ...
class MasseyModel(_Model): ...
class KeenerModel(_Model): ...
class ILsrModel(_Model): ...
class NashAveragingModel(_Model): ...
class OffenseDefenseModel(_Model): ...
class RandomWalkerModel(_Model): ...
class RankCentralityModel(_Model): ...
class SerialRankModel(_Model): ...
class ThurstoneMostellerModel(_Model): ...
class WhrModel(_Model): ...
class BordaModel(_Model): ...
class CopelandModel(_Model): ...
class BladeChestModel(_Model): ...
class EsRumModel(_Model): ...
class HodgeRankModel(_Model): ...
class KemenyModel(_Model): ...
class LsrModel(_Model): ...
class CovariateBtModel(_Model): ...
class WinRateModel(_Model): ...
class DuelingBanditModel(_Model): ...

# --------------------------------------------------------------------------- #
# Algorithms — games (online)
# --------------------------------------------------------------------------- #
class Elo:
    def __init__(self, *, k: float = ..., initial_rating: float = ..., scale: float = ...) -> None: ...
    def init(self) -> EloModel: ...
    def update(self, model: EloModel, data: GamesDataset) -> None: ...
    def fit(self, data: GamesDataset) -> EloModel: ...

class Glicko2:
    def __init__(self, *, tau: float = ..., rating: float = ..., rd: float = ..., sigma: float = ...) -> None: ...
    def init(self) -> Glicko2Model: ...
    def update(self, model: Glicko2Model, data: GamesDataset) -> None: ...
    def fit(self, data: GamesDataset) -> Glicko2Model: ...

class MovElo:
    def __init__(self, *, k: float = ..., initial_rating: float = ..., scale: float = ..., mov_exponent: float = ...) -> None: ...
    def init(self) -> MovEloModel: ...
    def update(self, model: MovEloModel, data: GamesDataset) -> None: ...
    def fit(self, data: GamesDataset) -> MovEloModel: ...

class MElo:
    def __init__(self, *, k: int = ..., lr_rating: float = ..., lr_vector: float = ..., initial_rating: float = ..., init_scale: float = ..., seed: int = ...) -> None: ...
    def init(self) -> MEloModel: ...
    def update(self, model: MEloModel, data: GamesDataset) -> None: ...
    def fit(self, data: GamesDataset) -> MEloModel: ...

class GeneralizedBt:
    def __init__(self, *, ties: str = ..., home: str = ..., iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: GamesDataset) -> GeneralizedBtModel: ...
    def fit_warm(self, data: GamesDataset, init: GeneralizedBtModel) -> GeneralizedBtModel: ...

class TeamBradleyTerry:
    def __init__(self, *, aggregate: str = ..., iterations: int = ..., tolerance: float = ..., ties: str = ...) -> None: ...
    def fit(self, data: GamesDataset) -> TeamBradleyTerryModel: ...
    def fit_warm(self, data: GamesDataset, init: TeamBradleyTerryModel) -> TeamBradleyTerryModel: ...

# --------------------------------------------------------------------------- #
# Algorithms — graph (batch)
# --------------------------------------------------------------------------- #
class PageRank:
    def __init__(self, *, damping: float = ..., iterations: int = ..., sink: str = ..., teleport: Teleport = ...) -> None: ...
    def fit(self, data: GraphDataset) -> PageRankModel: ...
    def fit_warm(self, data: GraphDataset, init: PageRankModel) -> PageRankModel: ...

class Hits:
    def __init__(self, *, iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: GraphDataset) -> HitsModel: ...
    def fit_warm(self, data: GraphDataset, init: HitsModel) -> HitsModel: ...

class BiRank:
    def __init__(self, *, iterations: int = ..., alpha: float = ..., beta: float = ..., seed: int = ...) -> None: ...
    def fit(self, data: GraphDataset) -> BiRankModel: ...
    def fit_warm(self, data: GraphDataset, init: BiRankModel) -> BiRankModel: ...

class Degree:
    def __init__(self, *, direction: str = ...) -> None: ...
    def fit(self, data: GraphDataset) -> DegreeModel: ...
    def fit_warm(self, data: GraphDataset, init: DegreeModel) -> DegreeModel: ...

class Harmonic:
    def __init__(self, *, direction: str = ..., cost: str = ..., sources: SourceBudget = ...) -> None: ...
    def fit(self, data: GraphDataset) -> HarmonicModel: ...
    def fit_warm(self, data: GraphDataset, init: HarmonicModel) -> HarmonicModel: ...

class Katz:
    def __init__(self, *, alpha: float = ..., iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: GraphDataset) -> KatzModel: ...
    def fit_warm(self, data: GraphDataset, init: KatzModel) -> KatzModel: ...

class KCore:
    def __init__(self) -> None: ...
    def fit(self, data: GraphDataset) -> KCoreModel: ...
    def fit_warm(self, data: GraphDataset, init: KCoreModel) -> KCoreModel: ...

class LeaderRank:
    def __init__(self, *, iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: GraphDataset) -> LeaderRankModel: ...
    def fit_warm(self, data: GraphDataset, init: LeaderRankModel) -> LeaderRankModel: ...

# --------------------------------------------------------------------------- #
# Algorithms — rewards / contextual (online)
# --------------------------------------------------------------------------- #
class Bandit:
    def __init__(self, *, policy: BanditPolicy = ..., seed: int = ...) -> None: ...
    def init(self) -> BanditModel: ...
    def update(self, model: BanditModel, data: RewardsDataset) -> None: ...
    def fit(self, data: RewardsDataset) -> BanditModel: ...

class SlidingWindowUcb:
    def __init__(self, *, window: int = ..., exploration: float = ...) -> None: ...
    def init(self) -> SlidingWindowUcbModel: ...
    def update(self, model: SlidingWindowUcbModel, data: RewardsDataset) -> None: ...
    def fit(self, data: RewardsDataset) -> SlidingWindowUcbModel: ...

class LinUcb:
    def __init__(self, *, alpha: float = ..., ridge: float = ...) -> None: ...
    def init(self) -> LinUcbModel: ...
    def update(self, model: LinUcbModel, data: ContextualRewardsDataset) -> None: ...
    def fit(self, data: ContextualRewardsDataset) -> LinUcbModel: ...

# --------------------------------------------------------------------------- #
# Algorithms — matchups (online)
# --------------------------------------------------------------------------- #
class WengLin:
    def __init__(self, *, variant: str = ..., mu: float = ..., sigma: float = ..., beta: float = ..., kappa: float = ..., epsilon: float = ..., tau: float = ..., gamma: str = ...) -> None: ...
    def init(self) -> WengLinModel: ...
    def update(self, model: WengLinModel, data: MatchupsDataset) -> None: ...
    def fit(self, data: MatchupsDataset) -> WengLinModel: ...

# --------------------------------------------------------------------------- #
# Algorithms — rankings (batch)
# --------------------------------------------------------------------------- #
class PlackettLuce:
    def __init__(self, *, iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: RankingsDataset) -> PlackettLuceModel: ...
    def fit_warm(self, data: RankingsDataset, init: PlackettLuceModel) -> PlackettLuceModel: ...

class Footrule:
    def __init__(self) -> None: ...
    def fit(self, data: RankingsDataset) -> FootruleModel: ...
    def fit_warm(self, data: RankingsDataset, init: FootruleModel) -> FootruleModel: ...

class Mallows:
    def __init__(self, *, passes: KemenyPasses = ..., seed: int = ...) -> None: ...
    def fit(self, data: RankingsDataset) -> MallowsModel: ...
    def fit_warm(self, data: RankingsDataset, init: MallowsModel) -> MallowsModel: ...

class Mc4:
    def __init__(self, *, damping: float = ..., iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: RankingsDataset) -> Mc4Model: ...
    def fit_warm(self, data: RankingsDataset, init: Mc4Model) -> Mc4Model: ...

# --------------------------------------------------------------------------- #
# Algorithms — trajectories
# --------------------------------------------------------------------------- #
class McValue:
    def __init__(self, *, gamma: float = ..., visit: str = ..., aggregate: str = ..., winsorize: Winsorize = ..., min_observations: int = ...) -> None: ...
    def fit(self, data: TrajectoriesDataset) -> McValueModel: ...
    def fit_warm(self, data: TrajectoriesDataset, init: McValueModel) -> McValueModel: ...

class BehaviorCloning:
    def __init__(self, *, granularity: Granularity = ..., smoothing: float = ...) -> None: ...
    def fit(self, data: TrajectoriesDataset) -> BehaviorCloningModel: ...
    def fit_warm(self, data: TrajectoriesDataset, init: BehaviorCloningModel) -> BehaviorCloningModel: ...

class ValueCompare:
    def __init__(self, *, gamma: float = ..., visit: str = ..., replicates: int = ..., method: str = ..., credible: float = ..., pairwise: PairwiseTests = ..., min_observations: int = ..., seed: int = ...) -> None: ...
    def fit(self, data: TrajectoriesDataset) -> ValueCompareModel: ...
    def fit_warm(self, data: TrajectoriesDataset, init: ValueCompareModel) -> ValueCompareModel: ...

class TdValue:
    def __init__(self, *, alpha: float = ..., gamma: float = ..., passes: int = ..., initial_value: float = ...) -> None: ...
    def init(self) -> TdValueModel: ...
    def update(self, model: TdValueModel, data: TrajectoriesDataset) -> None: ...
    def fit(self, data: TrajectoriesDataset) -> TdValueModel: ...

# --------------------------------------------------------------------------- #
# Algorithms — annotated (batch)
# --------------------------------------------------------------------------- #
class CrowdBt:
    def __init__(self, *, lambda_: float = ..., eta_prior_alpha: float = ..., eta_prior_beta: float = ..., iterations: int = ..., tolerance: float = ..., inner_sweeps: int = ...) -> None: ...
    def fit(self, data: AnnotatedPairsDataset) -> CrowdBtModel: ...
    def fit_warm(self, data: AnnotatedPairsDataset, init: CrowdBtModel) -> CrowdBtModel: ...

# --------------------------------------------------------------------------- #
# Algorithms — pairwise (batch unless noted)
# --------------------------------------------------------------------------- #
class BradleyTerryMM:
    def __init__(self, *, iterations: int = ..., tolerance: float = ..., min_graph_size: int = ..., remove_total_losers: bool = ..., create_fake_games: float = ..., random_subgraph_links: int = ..., random_subgraph_weight: float = ..., seed: int = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> BradleyTerryMMModel: ...
    def fit_warm(self, data: PairwiseDataset, init: BradleyTerryMMModel) -> BradleyTerryMMModel: ...

class BradleyTerryLR:
    def __init__(self, *, passes: int = ..., alpha: float = ..., decay: float = ..., thrifty: bool = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> BradleyTerryLRModel: ...
    def fit_warm(self, data: PairwiseDataset, init: BradleyTerryLRModel) -> BradleyTerryLRModel: ...

class BayesianBradleyTerry:
    def __init__(self, *, shape: float = ..., rate: float = ..., samples: int = ..., burn_in: int = ..., credible: float = ..., seed: int = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> BayesianBradleyTerryModel: ...
    def fit_warm(self, data: PairwiseDataset, init: BayesianBradleyTerryModel) -> BayesianBradleyTerryModel: ...

class Colley:
    def __init__(self, *, iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> ColleyModel: ...
    def fit_warm(self, data: PairwiseDataset, init: ColleyModel) -> ColleyModel: ...

class Massey:
    def __init__(self, *, iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> MasseyModel: ...
    def fit_warm(self, data: PairwiseDataset, init: MasseyModel) -> MasseyModel: ...

class Keener:
    def __init__(self, *, skew: bool = ..., normalize_games: bool = ..., iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> KeenerModel: ...
    def fit_warm(self, data: PairwiseDataset, init: KeenerModel) -> KeenerModel: ...

class ILsr:
    def __init__(self, *, outer: int = ..., inner_steps: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> ILsrModel: ...
    def fit_warm(self, data: PairwiseDataset, init: ILsrModel) -> ILsrModel: ...

class NashAveraging:
    def __init__(self, *, iterations: int = ..., tolerance: float = ..., learning_rate: float = ..., anneal_every: int = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> NashAveragingModel: ...
    def fit_warm(self, data: PairwiseDataset, init: NashAveragingModel) -> NashAveragingModel: ...

class OffenseDefense:
    def __init__(self, *, iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> OffenseDefenseModel: ...
    def fit_warm(self, data: PairwiseDataset, init: OffenseDefenseModel) -> OffenseDefenseModel: ...

class RandomWalker:
    def __init__(self, *, p: float = ..., iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> RandomWalkerModel: ...
    def fit_warm(self, data: PairwiseDataset, init: RandomWalkerModel) -> RandomWalkerModel: ...

class RankCentrality:
    def __init__(self, *, iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> RankCentralityModel: ...
    def fit_warm(self, data: PairwiseDataset, init: RankCentralityModel) -> RankCentralityModel: ...

class SerialRank:
    def __init__(self, *, iterations: int = ..., tolerance: float = ..., seed: int = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> SerialRankModel: ...
    def fit_warm(self, data: PairwiseDataset, init: SerialRankModel) -> SerialRankModel: ...

class ThurstoneMosteller:
    def __init__(self, *, iterations: int = ..., tolerance: float = ..., pseudo_count: float = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> ThurstoneMostellerModel: ...
    def fit_warm(self, data: PairwiseDataset, init: ThurstoneMostellerModel) -> ThurstoneMostellerModel: ...

class Whr:
    def __init__(self, *, w2: float = ..., prior_games: float = ..., iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> WhrModel: ...
    def fit_warm(self, data: PairwiseDataset, init: WhrModel) -> WhrModel: ...

class Borda:
    def __init__(self) -> None: ...
    def fit(self, data: PairwiseDataset) -> BordaModel: ...
    def fit_warm(self, data: PairwiseDataset, init: BordaModel) -> BordaModel: ...

class Copeland:
    def __init__(self) -> None: ...
    def fit(self, data: PairwiseDataset) -> CopelandModel: ...
    def fit_warm(self, data: PairwiseDataset, init: CopelandModel) -> CopelandModel: ...

class BladeChest:
    def __init__(self, *, dims: int = ..., variant: str = ..., lr: float = ..., epochs: int = ..., l2: float = ..., init_scale: float = ..., seed: int = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> BladeChestModel: ...
    def fit_warm(self, data: PairwiseDataset, init: BladeChestModel) -> BladeChestModel: ...

class EsRum:
    def __init__(self, *, distribution: str = ..., passes: int = ..., alpha: float = ..., gamma: float = ..., min_obs: int = ..., prior: int = ..., seed: int = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> EsRumModel: ...
    def fit_warm(self, data: PairwiseDataset, init: EsRumModel) -> EsRumModel: ...

class HodgeRank:
    def __init__(self, *, flow: str = ..., iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> HodgeRankModel: ...
    def fit_warm(self, data: PairwiseDataset, init: HodgeRankModel) -> HodgeRankModel: ...

class Kemeny:
    def __init__(self, *, passes: KemenyPasses = ..., min_obs: int = ..., algo: str = ..., seed: int = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> KemenyModel: ...
    def fit_warm(self, data: PairwiseDataset, init: KemenyModel) -> KemenyModel: ...

class Lsr:
    def __init__(self, *, steps: int = ..., estimator: str = ..., seed: int = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> LsrModel: ...
    def fit_warm(self, data: PairwiseDataset, init: LsrModel) -> LsrModel: ...

class CovariateBt:
    def __init__(self, features: list[tuple[str, list[float]]], *, l2: float = ..., intercepts: bool = ..., iterations: int = ..., tolerance: float = ...) -> None: ...
    def fit(self, data: PairwiseDataset) -> CovariateBtModel: ...
    def fit_warm(self, data: PairwiseDataset, init: CovariateBtModel) -> CovariateBtModel: ...

class WinRate:
    def __init__(self, *, confidence: str = ...) -> None: ...
    def init(self) -> WinRateModel: ...
    def update(self, model: WinRateModel, data: PairwiseDataset) -> None: ...
    def fit(self, data: PairwiseDataset) -> WinRateModel: ...

class DuelingBandit:
    def __init__(self, *, policy: DuelingPolicy = ..., seed: int = ...) -> None: ...
    def init(self) -> DuelingBanditModel: ...
    def update(self, model: DuelingBanditModel, data: PairwiseDataset) -> None: ...
    def fit(self, data: PairwiseDataset) -> DuelingBanditModel: ...

# --------------------------------------------------------------------------- #
# Free functions
# --------------------------------------------------------------------------- #
def wilson_interval(successes: float, failures: float, z: float = 1.96) -> tuple[float, float]: ...
def extract_components(graph: GraphDataset, min_size: int = 1) -> list[GraphDataset]: ...
def load_state(text: str) -> _Model: ...
